-- SAK-17243
alter table SAM_ATTACHMENT_T add ITEMTEXTID bigint(20) DEFAULT NULL;
alter table SAM_ITEMTEXT_T add REQUIRED_OPTIONS_COUNT int(11) DEFAULT NULL;
alter table SAM_ITEM_T add ANSWER_OPTIONS_RICH_COUNT int(11) DEFAULT NULL;
alter table SAM_ITEM_T add ANSWER_OPTIONS_SIMPLE_OR_RICH int(11) DEFAULT NULL;

create index SAM_ATTACH_ITEMTEXTID_I ON SAM_ATTACHMENT_T (ITEMTEXTID);
alter table SAM_ATTACHMENT_T add CONSTRAINT FOREIGN KEY (`ITEMTEXTID`) REFERENCES `SAM_ITEMTEXT_T` (`ITEMTEXTID`);

alter table SAM_PUBLISHEDATTACHMENT_T add `ITEMTEXTID` bigint(20) DEFAULT NULL;
alter table SAM_PUBLISHEDITEMTEXT_T add `REQUIRED_OPTIONS_COUNT` int(11) DEFAULT NULL;
alter table SAM_PUBLISHEDITEM_T add `ANSWER_OPTIONS_RICH_COUNT` int(11) DEFAULT NULL;
alter table SAM_PUBLISHEDITEM_T add `ANSWER_OPTIONS_SIMPLE_OR_RICH` int(11) DEFAULT NULL;

create index SAM_PUBATTACH_ITEMTEXTID_I ON SAM_PUBLISHEDATTACHMENT_T (ITEMTEXTID);
alter table SAM_PUBLISHEDATTACHMENT_T add CONSTRAINT FOREIGN KEY (`ITEMTEXTID`) REFERENCES `SAM_PUBLISHEDITEMTEXT_T` (`ITEMTEXTID`);

